version: "3"

services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    restart: always
    ports:
      - 3005:3005
    command:
      - npm run start:dev

  makefilm_db:
    image: postgres:13
    container_name: makefilm_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: poll_db
      POSTGRES_USER: poll_user
      POSTGRES_PASSWORD: poll_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
