version: "3"

services:
  lint:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: lint

  build:
    image: makefilm/api
    container_name: makefilm-api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build

  unit_tests:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: unit_tests

  e2e_tests:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: e2e_tests

  prod:
    image: makefilm/api
    container_name: makefilm-api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    restart: always
    ports:
      - 3005:3005

  makefilm_db:
    image: postgres:13
    container_name: makefilm_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: poll_db
      POSTGRES_USER: poll_user
      POSTGRES_PASSWORD: poll_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
