version: "3"

services:
  lint:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: lint
    command: npm run lint

  build:
    image: makefilm/api
    container_name: makefilm-api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build
    command: npm run build

  e2e:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: test
    command: npm run test:e2e

  api:
    image: makefilm/api
    container_name: makefilm-api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build
    restart: always
    command: npm run build
    ports:
      - 3005:3005

  makefilm_db:
    image: postgres:13
    container_name: makefilm_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: poll_db
      POSTGRES_USER: poll_user
      POSTGRES_PASSWORD: poll_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
