version: '3.8'

services:
  api-release:
    image: makefilm/api
    container_name: makefilm-api
    build:
      context: ../../../
      dockerfile: ./apps/api/Dockerfile
      target: prod
    restart: always
