name: Makefilm

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_APP_NAME: "api"
          envkey_APP_URL: 'http://localhost:3005'
          envkey_APP_PORT: 3005
          envkey_API_PREFIX: api

      - name: Set up Docker Compose
        run: docker compose --env-file ./.env -f docker-compose.yml run lint

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs:
      - lint

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_APP_NAME: "api"
          envkey_APP_URL: 'http://localhost:3005'
          envkey_APP_PORT: 3005
          envkey_API_PREFIX: api

      - name: Set up Docker Compose
        run: docker compose --env-file ./.env -f docker-compose.yml run build

  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_APP_NAME: "api"
          envkey_APP_URL: 'http://localhost:3005'
          envkey_APP_PORT: 3005
          envkey_API_PREFIX: api

      - name: Set up Docker Compose
        run: docker compose --env-file ./.env -f docker-compose.yml run e2e

  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs:
      - e2e-tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_APP_NAME: "api"
          envkey_APP_URL: 'http://localhost:3005'
          envkey_APP_PORT: 3005
          envkey_API_PREFIX: api

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build and Tag Docker Image
        run: |
          docker compose --env-file ./.env -f docker-compose.yml build api
          docker tag makefilm/api ghcr.io/alexsergey/makefilm-api:latest

      - name: Push Docker Image to GitHub Container Registry
        run: docker push ghcr.io/alexsergey/makefilm-api:latest
