name: Deployment pipeline for Master/Dev

on:
  push:
    branches:
      - master
      - dev

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose -f ci/docker-compose.lint.yml run lint

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose -f ci/docker-compose.build.yml run build

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose -f ci/docker-compose.unit-tests.yml run unit_tests

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose -f apps/api-e2e/ci/docker-compose.e2e-tests.yml run e2e_tests

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: e2e-tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Show me the version
        run: 'echo "Current version: ${{ steps.package-version.outputs.current-version }}"'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build and Tag Docker Image
        run: |
          docker compose -f apps/api/ci/docker-compose.release.yml build release
          docker tag makefilm/api ghcr.io/alexsergey/makefilm-api:latest

      - name: Push Docker Image to GitHub Container Registry
        run: docker push ghcr.io/alexsergey/makefilm-api:latest

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: release
    if: |
      github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to production (master)
        if: github.ref == 'refs/heads/master'
        run: echo "Deploying to production environment (master)..."

      - name: Deploy to staging (dev)
        if: github.ref == 'refs/heads/dev'
        run: echo "Deploying to staging environment (dev)..."
