name: Common Docker Steps

on:
  workflow_call:
    inputs:
      docker_file:
        required: true
        type: string
      container_name:
        required: true
        type: string

jobs:
  common-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose -f ${{ inputs.docker_file }} run ${{ inputs.container_name }}

      - name: Clean up containers
        run: |
          docker compose -f ${{ inputs.docker_file }} down ${{ inputs.container_name }}
