name: Verification pipeline for each PR

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - master
      - dev

jobs:
  lint:
    name: Lint Code
    uses: ./common.yml
    with:
      docker_file: ci/docker-compose.lint.yml
      container_name: lint

  build:
    name: Build Application
    needs: lint
    uses: ./common.yml
    with:
      docker_file: ci/docker-compose.build.yml
      container_name: build

  unit-tests:
    name: Unit Tests
    needs: build
    uses: ./common.yml
    with:
      docker_file: ci/docker-compose.unit-tests.yml
      container_name: unit_tests

  api-e2e-tests:
    name: API E2E Tests
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: NODE_ENV=test DATABASE_PORT=5433 DATABASE_URL="postgresql://poll_user:poll_password@makefilm_db_test:5432/poll_db?schema=public" docker compose --env-file .env up --abort-on-container-exit database migrations api api-e2e

      - name: Clean up containers
        run: |
          docker compose down database migrations api api-e2e
