name: Verification pipeline for each PR

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose -f ci/docker-compose.lint.yml run lint

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose -f ci/docker-compose.build.yml run build

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
      - run: echo "E2E tests running"
      - parallel:
          branch_id_1:
            steps:
              - run: echo "branch 1 sequential step 1"
              - run: echo "branch 1 sequential step 2"

            branch_id_2:
              steps:
                - run: echo "branch 2 sequential step 1"
                - run: echo "branch 2 sequential step 2"

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: NODE_ENV=test DATABASE_PORT=5433 DATABASE_URL="postgresql://poll_user:poll_password@makefilm_db_test:5432/poll_db?schema=public" docker-compose --env-file .env up -d database migrations api api-e2e
